version: '3.7'

services:
  webapi:
    build: .
    ports:
      - "5000:80"
      - "5001:443"
    environment: # see https://github.com/dotnet/dotnet-docker/blob/main/samples/run-aspnetcore-https-development.md#linux
      ASPNETCORE_HTTPS_PORT: 5001
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "https://+:443;http://+:80"
      ASPNETCORE_Kestrel__Certificates__Development__Password: "12345"
      MINIO_ENDPOINT: "${MINIO_ENDPOINT}" # change according your need, @see https://github.com/minio/minio/issues/8007
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
      MSSQL_DB: "${MSSQL_DB}"
      MSSQL_USER: "${MSSQL_USER}"
      MSSQL_PASS: "${MSSQL_PASS}"
      MSSQL_PORT: "${MSSQL_PORT}"
      MSSQL_HOST: "${MSSQL_HOST}"
    # depends_on:
      # - sqlserver
      # - minios3
  
  sqlserver:
    build: 
      context: .
      dockerfile: sqlserver.Dockerfile # @see https://docs.docker.com/compose/compose-file/compose-file-v3/#context
    ports:
      - "${MSSQL_PORT}:1433"
    environment:
      SA_PASSWORD: "12345!@Local"
      ACCEPT_EULA: "Y"

  
  # https://docs.min.io/docs/deploy-minio-on-docker-compose.html
  # see more https://github.com/minio/minio/issues/4769#issuecomment-331033735
  minios3:
    image: minio/minio
    entrypoint: /bin/sh
    command: -c 'mkdir -p /data/coba-bucket && /usr/bin/docker-entrypoint.sh server /data --console-address ":9001"'
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"  
    volumes:
      - ./nats/nats-server.conf:/nats-server.conf
  