version: '3.7'

services:
  webapi:
    build: .
    ports:
      - "5001:80"
    depends_on:
      - sqlserver
      - minios3
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "12345!@Local"
      ACCEPT_EULA: "Y"

  
  # https://docs.min.io/docs/deploy-minio-on-docker-compose.html
  # see more https://github.com/minio/minio/issues/4769#issuecomment-331033735
  minios3:
    image: minio/minio
    entrypoint: /bin/sh
    command: -c 'mkdir -p /data/coba-bucket && /usr/bin/minio server /data --console-address ":9001"'
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_ACCESS_KEY: "api-coba"
      MINIO_SECRET_KEY: "cUQ4A6ytTPrY5jt"
      